### PR TITLE
RHCLOUD-34502 Send a notification everytime there is a change in the relationship

### PR DESCRIPTION
**Pull request by josejulio**
## Describe your changes

- Adding the k8spolicy_ispropagatedto_k8scluster relationship resource from end to end (create) up to the kafka event

This POST input (found in data/k8spolicy_ispropagatedto_k8scluster.json):

```json
{
  "k8spolicy_ispropagatedto_k8scluster": {
    "metadata": {
    },
    "reporter_data": {
      "reporter_type": "OCM",
      "reporter_version": "0.1",
      "subject_local_resource_id": "1",
      "object_local_resource_id": "2"
    },
    "relationship_data": {
      "status": "COMPLIANT"
    }
  }
}
```

yields:

```json
{
   "specversion":"1.0",
   "id":"807cac08-75d2-11ef-9038-a63ce1be7759",
   "source":"http://localhost:8081",
   "type":"redhat.inventory.resources_relationship.k8s-policy_ispropagatedto_k8s-cluster.created",
   "subject":"/resources_relationship/k8s-policy_ispropagatedto_k8s-cluster/1",
   "datacontenttype":"application/json",
   "time":"2024-09-18T15:27:23.090651146Z",
   "data":{
      "metadata":{
         "id":13,
         "last_reported":"2024-09-18T09:27:23.090651146-06:00",
         "relationship_type":"k8s-policy_ispropagatedto_k8s-cluster"
      },
      "reporter_data":{
         "reporter_instance_id":"curl/8.6.0",
         "reporter_type":"OCM",
         "last_reported":"2024-09-18T09:27:23.09097916-06:00",
         "subject_local_resource_id":"1",
         "object_local_resource_id":"2",
         "reporter_version":"0.1"
      },
      "relationship_data":{
         "status":"COMPLIANT",
         "k8s_policy_id":0,
         "k8s_cluster_id":0
      }
   }
}
```

## Ticket reference (if applicable)
Fixes #

## Checklist

* [ ] Are the agreed upon acceptance criteria fulfilled?

* [ ] Was the 4-eye-principle applied? (async PR review, pairing, ensembling)

* [ ] Do your changes have passing automated tests and sufficient observability?

* [ ] Are the work steps you introduced repeatable by others, either through automation or documentation?
  * [ ] If automation is possible but not done due to other constraints, a ticket to the tech debt sprint is added
  * [ ] An SOP (Standard Operating Procedure) was created

* [ ] The Changes were automatically built, tested, and  - if needed, behind a feature flag - deployed to our production environment. (**Please check this when the new deployment is done and you could verify it.**)

* [ ] Are the agreed upon coding/architectural practices applied?

* [ ] Are security needs fullfilled? (e.g. no internal URL)

* [ ] Is the corresponding Ticket in the right state? (should be on "review" now, put to done when this change made it to production)

* [ ] For changes to the public API / code dependencies: Was the whole team (or a sufficient amount of ppl) able to review?

### CODE REVIEW

**Comment by gwenneg** [comment]
This PR depends on a previous version of the Konflux pipeline definitions which no longer work in Konflux. Rebasing it might fix that (I'm not sure).

**Comment by josejulio** [comment]
> This PR depends on a previous version of the Konflux pipeline definitions which no longer work in Konflux. Rebasing it might fix that (I'm not sure). If it doesn't, it's no big deal, you can simply ignore the failed check in GitHub since Konflux isn't 100% stable for inventory-api yet.

rebasing did the trick - thanks!

**Review by jmelis — APPROVED** [review]
LGTM

**Pull request merged**
